In [453]:
import sklearn

In [454]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

In [455]:

data = pd.read_excel(r"C:\Users\USER\Documents\student_data\project26.xlsx")

In [456]:

data

,Timestamp,CGPA,attendance,Hours_of_study,Gender,Age,contribution_in _class,level_of_study,Parent/Guardian_ Level_ofeducation,financial_difficulties,access_to_ a_ computer,pass _or_fail
0,2026-05-02 10:29:44.134,1.6 - 3.0,35,2-3,male,21,rarely,400,Secondary education,Strongly Agree,yes,NO
1,2026-05-02 10:35:13.145,1.6 - 3.0,60,2-3,male,21,sometimes,400,Secondary education,Agree,yes,YES
2,2026-05-02 10:36:06.309,3 - 4.5,70,0-1,Female,20,often,400,Bachelor's degree,Neutral,yes,YES
3,2026-05-02 10:44:29.288,3 - 4.5,70,2-3,male,21,always,400,Bachelor's degree,Agree,yes,YES
4,2026-05-02 10:46:37.171,1.6 - 3.0,70,0-1,male,20,often,400,Bachelor's degree,Strongly Agree,yes,YES
...,...,...,...,...,...,...,...,...,...,...,...,...
206,2026-06-15 21:54:05.987,4.6 - 5.0,98,2-3,Female,18,always,300,Bachelor's degree,Strongly Disagree,yes,YES
207,2026-06-15 21:54:58.066,4.6 - 5.0,90,2-3,male,20,often,400,Secondary education,Agree,yes,YES
208,2026-06-15 21:55:40.313,0 - 1.5,25,0-1,male,20,rarely,400,Bachelor's degree,Neutral,yes,NO
209,2026-06-15 21:56:24.433,1.6 - 3.0,70,0-1,male,20,sometimes,300,Secondary education,Disagree,yes,NO
210,2026-06-15 21:57:03.560,3 - 4.5,85,2-3,Female,19,sometimes,400,Bachelor's degree,Neutral,yes,YES

In [457]:
data.info

<bound method DataFrame.info of                   Timestamp       CGPA  attendance Hours_of_study  Gender  \
0   2026-05-02 10:29:44.134  1.6 - 3.0          35            2-3    male
1   2026-05-02 10:35:13.145  1.6 - 3.0          60            2-3    male
2   2026-05-02 10:36:06.309    3 - 4.5          70            0-1  Female
3   2026-05-02 10:44:29.288    3 - 4.5          70            2-3    male
4   2026-05-02 10:46:37.171  1.6 - 3.0          70            0-1    male
..                      ...        ...         ...            ...     ...
206 2026-06-15 21:54:05.987  4.6 - 5.0          98            2-3  Female
207 2026-06-15 21:54:58.066  4.6 - 5.0          90            2-3    male
208 2026-06-15 21:55:40.313    0 - 1.5          25            0-1    male
209 2026-06-15 21:56:24.433  1.6 - 3.0          70            0-1    male
210 2026-06-15 21:57:03.560    3 - 4.5          85            2-3  Female

     Age contribution_in _class  level_of_study  \
0     21                 rarely             400
1     21              sometimes             400
2     20                  often             400
3     21                 always             400
4     20                  often             400
..   ...                    ...             ...
206   18                 always             300
207   20                  often             400
208   20                 rarely             400
209   20              sometimes             300
210   19              sometimes             400

    Parent/Guardian_ Level_ofeducation financial_difficulties  \
0                  Secondary education         Strongly Agree
1                  Secondary education                  Agree
2                    Bachelor's degree                Neutral
3                    Bachelor's degree                  Agree
4                    Bachelor's degree         Strongly Agree
..                                 ...                    ...
206                  Bachelor's degree      Strongly Disagree
207                Secondary education                  Agree
208                  Bachelor's degree                Neutral
209                Secondary education               Disagree
210                  Bachelor's degree                Neutral

    access_to_ a_ computer pass _or_fail
0                      yes            NO
1                      yes           YES
2                      yes           YES
3                      yes           YES
4                      yes           YES
..                     ...           ...
206                    yes           YES
207                    yes           YES
208                    yes            NO
209                    yes            NO
210                    yes           YES

[211 rows x 12 columns]>

In [458]:
data['CGPA'].unique()

array(['1.6 - 3.0', '3 - 4.5', '4.6 - 5.0', '0 - 1.5'], dtype=object)

In [459]:
CGPA_dummy = pd.get_dummies(data['CGPA'],drop_first= True).astype(int)

In [460]:
CGPA_dummy

     1.6 - 3.0  3 - 4.5  4.6 - 5.0
0            1        0          0
1            1        0          0
2            0        1          0
3            0        1          0
4            1        0          0
..         ...      ...        ...
206          0        0          1
207          0        0          1
208          0        0          0
209          1        0          0
210          0        1          0

[211 rows x 3 columns]

In [461]:
data['CGPA'].unique()

array(['1.6 - 3.0', '3 - 4.5', '4.6 - 5.0', '0 - 1.5'], dtype=object)

In [462]:
CGPA_dummy = pd.get_dummies(data['CGPA'],drop_first= True).astype(int)

In [463]:
CGPA_dummy

     1.6 - 3.0  3 - 4.5  4.6 - 5.0
0            1        0          0
1            1        0          0
2            0        1          0
3            0        1          0
4            1        0          0
..         ...      ...        ...
206          0        0          1
207          0        0          1
208          0        0          0
209          1        0          0
210          0        1          0

[211 rows x 3 columns]

In [464]:
data['Hours_of_study'].unique()

array(['2-3', '0-1', '4-5', ' 4-5', '6 & above'], dtype=object)

In [465]:
Hours_of_study_dummy = pd.get_dummies(data['Hours_of_study'],drop_first= False).astype(int)

In [466]:
Hours_of_study_dummy

      4-5  0-1  2-3  4-5  6 & above
0       0    0    1    0          0
1       0    0    1    0          0
2       0    1    0    0          0
3       0    0    1    0          0
4       0    1    0    0          0
..    ...  ...  ...  ...        ...
206     0    0    1    0          0
207     0    0    1    0          0
208     0    1    0    0          0
209     0    1    0    0          0
210     0    0    1    0          0

[211 rows x 5 columns]

In [467]:
data['Gender'].unique()

array(['male', 'Female'], dtype=object)

In [468]:
Gender_dummy = pd.get_dummies(data['Gender'],drop_first= True).astype(int)

In [469]:
Gender_dummy

     male
0       1
1       1
2       0
3       1
4       1
..    ...
206     0
207     1
208     1
209     1
210     0

[211 rows x 1 columns]

In [470]:
data['Gender'].value_counts()

Gender
male      113
Female     98
Name: count, dtype: int64

In [471]:
data['contribution_in _class'].unique()

array(['rarely', 'sometimes', 'often', 'always'], dtype=object)

In [472]:
contribution_dummy = pd.get_dummies(data['contribution_in _class'],drop_first= False).astype(int)

In [473]:
contribution_dummy

     always  often  rarely  sometimes
0         0      0       1          0
1         0      0       0          1
2         0      1       0          0
3         1      0       0          0
4         0      1       0          0
..      ...    ...     ...        ...
206       1      0       0          0
207       0      1       0          0
208       0      0       1          0
209       0      0       0          1
210       0      0       0          1

[211 rows x 4 columns]

In [474]:
data['Parent/Guardian_ Level_ofeducation'].unique()

array(['Secondary education', "Bachelor's degree", 'Postgraduate degree',
       'Primary education', 'No formal education'], dtype=object)

In [475]:
Parent_Guardian_dummy = pd.get_dummies(data['Parent/Guardian_ Level_ofeducation'],drop_first= False).astype(int)

In [476]:
Parent_Guardian_dummy

,Bachelor's degree,No formal education,Postgraduate degree,Primary education,Secondary education
0,0,0,0,0,1
1,0,0,0,0,1
2,1,0,0,0,0
3,1,0,0,0,0
4,1,0,0,0,0
...,...,...,...,...,...
206,1,0,0,0,0
207,0,0,0,0,1
208,1,0,0,0,0
209,0,0,0,0,1
210,1,0,0,0,0

In [477]:
data['financial_difficulties'].unique()

array(['Strongly Agree', 'Agree', 'Neutral', 'Disagree',
       'Strongly Disagree'], dtype=object)

In [478]:
financial_difficulties_dummy = pd.get_dummies(data['financial_difficulties'],drop_first= False).astype(int)

In [479]:
financial_difficulties_dummy

     Agree  Disagree  Neutral  Strongly Agree  Strongly Disagree
0        0         0        0               1                  0
1        1         0        0               0                  0
2        0         0        1               0                  0
3        1         0        0               0                  0
4        0         0        0               1                  0
..     ...       ...      ...             ...                ...
206      0         0        0               0                  1
207      1         0        0               0                  0
208      0         0        1               0                  0
209      0         1        0               0                  0
210      0         0        1               0                  0

[211 rows x 5 columns]

In [480]:
data['access_to_ a_ computer'].unique()

array(['yes', 'no'], dtype=object)

In [481]:
access_computer_dummy = pd.get_dummies(data['access_to_ a_ computer'],drop_first= True).astype(int)

In [482]:
access_computer_dummy

     yes
0      1
1      1
2      1
3      1
4      1
..   ...
206    1
207    1
208    1
209    1
210    1

[211 rows x 1 columns]

In [483]:
data = pd.concat([data,CGPA_dummy,Hours_of_study_dummy,Gender_dummy,contribution_dummy,Parent_Guardian_dummy,financial_difficulties_dummy,access_computer_dummy],axis="columns")

In [484]:
data

,Timestamp,CGPA,attendance,Hours_of_study,Gender,Age,contribution_in _class,level_of_study,Parent/Guardian_ Level_ofeducation,financial_difficulties,...,No formal education,Postgraduate degree,Primary education,Secondary education,Agree,Disagree,Neutral,Strongly Agree,Strongly Disagree,yes
0,2026-05-02 10:29:44.134,1.6 - 3.0,35,2-3,male,21,rarely,400,Secondary education,Strongly Agree,...,0,0,0,1,0,0,0,1,0,1
1,2026-05-02 10:35:13.145,1.6 - 3.0,60,2-3,male,21,sometimes,400,Secondary education,Agree,...,0,0,0,1,1,0,0,0,0,1
2,2026-05-02 10:36:06.309,3 - 4.5,70,0-1,Female,20,often,400,Bachelor's degree,Neutral,...,0,0,0,0,0,0,1,0,0,1
3,2026-05-02 10:44:29.288,3 - 4.5,70,2-3,male,21,always,400,Bachelor's degree,Agree,...,0,0,0,0,1,0,0,0,0,1
4,2026-05-02 10:46:37.171,1.6 - 3.0,70,0-1,male,20,often,400,Bachelor's degree,Strongly Agree,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,2026-06-15 21:54:05.987,4.6 - 5.0,98,2-3,Female,18,always,300,Bachelor's degree,Strongly Disagree,...,0,0,0,0,0,0,0,0,1,1
207,2026-06-15 21:54:58.066,4.6 - 5.0,90,2-3,male,20,often,400,Secondary education,Agree,...,0,0,0,1,1,0,0,0,0,1
208,2026-06-15 21:55:40.313,0 - 1.5,25,0-1,male,20,rarely,400,Bachelor's degree,Neutral,...,0,0,0,0,0,0,1,0,0,1
209,2026-06-15 21:56:24.433,1.6 - 3.0,70,0-1,male,20,sometimes,300,Secondary education,Disagree,...,0,0,0,1,0,1,0,0,0,1
210,2026-06-15 21:57:03.560,3 - 4.5,85,2-3,Female,19,sometimes,400,Bachelor's degree,Neutral,...,0,0,0,0,0,0,1,0,0,1

In [485]:
data_new =data.drop(["Timestamp","CGPA",'Hours_of_study','contribution_in _class','Gender','Parent/Guardian_ Level_ofeducation','financial_difficulties','access_to_ a_ computer'],axis="columns")

In [486]:
data_new

,attendance,Age,level_of_study,pass _or_fail,1.6 - 3.0,3 - 4.5,4.6 - 5.0,4-5,0-1,2-3,...,No formal education,Postgraduate degree,Primary education,Secondary education,Agree,Disagree,Neutral,Strongly Agree,Strongly Disagree,yes
0,35,21,400,NO,1,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,1
1,60,21,400,YES,1,0,0,0,0,1,...,0,0,0,1,1,0,0,0,0,1
2,70,20,400,YES,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,70,21,400,YES,0,1,0,0,0,1,...,0,0,0,0,1,0,0,0,0,1
4,70,20,400,YES,1,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,98,18,300,YES,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,1
207,90,20,400,YES,0,0,1,0,0,1,...,0,0,0,1,1,0,0,0,0,1
208,25,20,400,NO,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
209,70,20,300,NO,1,0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
210,85,19,400,YES,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1

In [487]:
data_new2 = data_new.dropna()

In [488]:
data_new2

,attendance,Age,level_of_study,pass _or_fail,1.6 - 3.0,3 - 4.5,4.6 - 5.0,4-5,0-1,2-3,...,No formal education,Postgraduate degree,Primary education,Secondary education,Agree,Disagree,Neutral,Strongly Agree,Strongly Disagree,yes
0,35,21,400,NO,1,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,1
1,60,21,400,YES,1,0,0,0,0,1,...,0,0,0,1,1,0,0,0,0,1
2,70,20,400,YES,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,70,21,400,YES,0,1,0,0,0,1,...,0,0,0,0,1,0,0,0,0,1
4,70,20,400,YES,1,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,98,18,300,YES,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,1
207,90,20,400,YES,0,0,1,0,0,1,...,0,0,0,1,1,0,0,0,0,1
208,25,20,400,NO,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
209,70,20,300,NO,1,0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
210,85,19,400,YES,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1

In [489]:
data_new2['pass _or_fail'].unique()

array(['NO', 'YES'], dtype=object)

In [490]:
pass_or_fail_dummy = pd.get_dummies(data['pass _or_fail'],drop_first= True).astype(int)

In [491]:
pass_or_fail_dummy

     YES
0      0
1      1
2      1
3      1
4      1
..   ...
206    1
207    1
208    0
209    0
210    1

[211 rows x 1 columns]

In [492]:
data_combined = pd.concat([data_new.drop("pass _or_fail", axis=1), pass_or_fail_dummy ],axis=1)

In [493]:
data_combined

,attendance,Age,level_of_study,1.6 - 3.0,3 - 4.5,4.6 - 5.0,4-5,0-1,2-3,4-5,...,Postgraduate degree,Primary education,Secondary education,Agree,Disagree,Neutral,Strongly Agree,Strongly Disagree,yes,YES
0,35,21,400,1,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,1,0
1,60,21,400,1,0,0,0,0,1,0,...,0,0,1,1,0,0,0,0,1,1
2,70,20,400,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,1,1
3,70,21,400,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,1,1
4,70,20,400,1,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,98,18,300,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,1,1,1
207,90,20,400,0,0,1,0,0,1,0,...,0,0,1,1,0,0,0,0,1,1
208,25,20,400,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,1,0
209,70,20,300,1,0,0,0,1,0,0,...,0,0,1,0,1,0,0,0,1,0
210,85,19,400,0,1,0,0,0,1,0,...,0,0,0,0,0,1,0,0,1,1

In [494]:
data_combined2 = data_combined.dropna()

In [495]:
data_combined2

,attendance,Age,level_of_study,1.6 - 3.0,3 - 4.5,4.6 - 5.0,4-5,0-1,2-3,4-5,...,Postgraduate degree,Primary education,Secondary education,Agree,Disagree,Neutral,Strongly Agree,Strongly Disagree,yes,YES
0,35,21,400,1,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,1,0
1,60,21,400,1,0,0,0,0,1,0,...,0,0,1,1,0,0,0,0,1,1
2,70,20,400,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,1,1
3,70,21,400,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,1,1
4,70,20,400,1,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,98,18,300,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,1,1,1
207,90,20,400,0,0,1,0,0,1,0,...,0,0,1,1,0,0,0,0,1,1
208,25,20,400,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,1,0
209,70,20,300,1,0,0,0,1,0,0,...,0,0,1,0,1,0,0,0,1,0
210,85,19,400,0,1,0,0,0,1,0,...,0,0,0,0,0,1,0,0,1,1

In [496]:
x = data_combined.drop("YES",axis="columns").values
y = data_combined['YES']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=30)
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(X_train)

In [497]:
data_combined[data_combined.isnull().any(axis=1)]

Empty DataFrame
Columns: [attendance, Age, level_of_study, 1.6 - 3.0, 3 - 4.5, 4.6 - 5.0,  4-5, 0-1, 2-3, 4-5, 6 & above, male, always, often, rarely, sometimes, Bachelor's degree, No formal education, Postgraduate degree, Primary education, Secondary education, Agree, Disagree, Neutral, Strongly Agree, Strongly Disagree, yes, YES]
Index: []

[0 rows x 28 columns]

In [498]:
data_combined2 = data_combined.dropna()

In [499]:
model = LogisticRegression()
model.fit(x_train_scaled,y_train)
y_predited = model.predict(X_test)

In [500]:
accuracy_score(y_test,y_predited)

0.7906976744186046

In [501]:
model_2 = DecisionTreeClassifier()
model_2.fit(X_train ,y_train)
y_predited_2 =model_2.predict(X_test)

In [502]:
accuracy_score(y_test,y_predited_2)

0.9302325581395349

In [507]:
model_3 = RandomForestClassifier()
model_3.fit(X_train,y_train)
y_predited_3 = model_3.predict(X_test)

In [508]:
accuracy_score(y_test,y_predited_3)

0.9302325581395349

In [509]:
zpo=classification_report(y_test,y_predited_3)

In [510]:
print(zpo)

              precision    recall  f1-score   support

           0       0.88      0.78      0.82         9
           1       0.94      0.97      0.96        34

    accuracy                           0.93        43
   macro avg       0.91      0.87      0.89        43
weighted avg       0.93      0.93      0.93        43

In [511]:
confusion_matrix(y_test,y_predited_3)

array([[ 7,  2],
       [ 1, 33]])

In [515]:
zpo2=classification_report(y_test,y_predited_2)

In [516]:
print(zpo2)

              precision    recall  f1-score   support

           0       0.80      0.89      0.84         9
           1       0.97      0.94      0.96        34

    accuracy                           0.93        43
   macro avg       0.88      0.92      0.90        43
weighted avg       0.93      0.93      0.93        43

In [518]:
confusion_matrix(y_test,y_predited_2)

array([[ 8,  1],
       [ 2, 32]])

In [521]:
zpo3=classification_report(y_test,y_predited)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [522]:
print(zpo3)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.79      1.00      0.88        34

    accuracy                           0.79        43
   macro avg       0.40      0.50      0.44        43
weighted avg       0.63      0.79      0.70        43

In [523]:
confusion_matrix(y_test,y_predited)

array([[ 0,  9],
       [ 0, 34]])